### ISSUE TITLE
Voting

### ISSUE THREAD

**Issue by aarondunn** [musopen/shiny-dubstep#1]
Can we change this to a heart icon like the new Itunes Music, and then we just go from empty to full like: 

![image](https://cloud.githubusercontent.com/assets/3102237/9078719/23c0e220-3af7-11e5-8bc2-6e7ff1295673.png)
![image](https://cloud.githubusercontent.com/assets/3102237/9078720/2a154d1e-3af7-11e5-8688-591038d721c1.png)

more simple that way for users

**Comment by n3lab** [comment]
Added, but temporarily it isn't look like your images. I ll try to find the same. And this icon is too small for retina screens.

**Comment by aarondunn** [comment]
what kind of images can it support? Does it support icons fonts? There are hearts here: http://fontello.com/
also
http://fortawesome.github.io/Font-Awesome/icons/

**Comment by n3lab** [comment]
Added from http://fortawesome.github.io/Font-Awesome/icons/.
