### ISSUE TITLE
Do we have any analytics here?

### ISSUE THREAD

**Issue by aarondunn** [musopen/shiny-dubstep#4]
Can we add Mixpanel + Google Analytics so we can track things like
- # of users
- How often each feature is used?
- I bet we can even get data about how often some pieces are skipped or favorited if we want to

**Comment by aarondunn** [comment]
Here are the integration details for each, once you are ready:


Google Analytics:
Tracking ID: UA-574070-10
Tracking code and instructions: https://goo.gl/gQFkKL
Guide: https://developers.google.com/analytics/devguides/collection/ios/v3/

Mixpanel:
Instructions: https://mixpanel.com/help/reference/ios
Token: 795ce95f841e32264312cc32148a75c4

Note we ideally want to track both users (people) and events separately so we can see who is doing what.

**Comment by n3lab** [comment]
Is it possible give me accounts and passwords to check web-interface, when i ll add analytics? It will be good for testing.

**Comment by aarondunn** [comment]
Sure I can do that. whats your email?

**Comment by n3lab** [comment]
n3laboratory@gmail.com

**Comment by aarondunn** [comment]
ok added to both

**Comment by n3lab** [comment]
Done. Added Mixpanel + Google Analytics.
Mixpanel tracks user actions (Segmentation and Retention menus in web-interface).
Google Analytics tracks users and screens.
