### ISSUE TITLE
Can we crop backgrounds so they don't stretch?

### ISSUE THREAD

**Issue by aarondunn** [musopen/shiny-dubstep#8]
For example, i tested with this background: http://imgur.com/8wtBqbv

I'm thinking for ipad/iphone since we have to support different sizes, maybe cropping is best? Or should i give different sizes for different devices?

**Comment by n3lab** [comment]
Done. Now backgounds are cropped to fit screen. Maybe will be better to add diff size to each device, depends on what images you want to add as background.
